Repository AY1920S1-CS2103-T11-3/main, pull requests merged in 2019-11, with the labels that each got.

#112 Fix more dry PE issues
  docs/UserGuide.adoc
  src/main/java/seedu/system/logic/commands/insession/EndSessionCommand.java
  src/main/java/seedu/system/logic/commands/outofsession/AddParticipationCommand.java
  src/main/java/seedu/system/logic/commands/outofsession/DeleteCompetitionCommand.java
  src/main/java/seedu/system/logic/commands/outofsession/EditParticipationCommand.java
  src/main/java/seedu/system/logic/commands/outofsession/EditPersonCommand.java
  src/main/java/seedu/system/logic/commands/outofsession/ListParticipationCommand.java
  src/main/java/seedu/system/logic/parser/ParserUtil.java
  src/main/java/seedu/system/model/ModelManager.java
  src/main/java/seedu/system/model/person/Name.java
  src/main/java/seedu/system/ui/ParticipationCard.java
Labels: priority.High, severity.High, type.Bug

#120 Update Developer Guide (incomplete)
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ActivityDiagram.png
  docs/images/SessionClassDiagram.png
Labels: priority.High, type.Task

#126 Update session features to DG
  docs/DeveloperGuide.adoc
  docs/images/LiftSequenceDiagram.png
  docs/images/NextSequenceDiagram.png
  docs/images/StartSequenceDiagram.png
  src/main/java/seedu/system/model/session/Session.java
Labels: type.Task

#137 Add documentation for find participation and find competition commands
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/shawnkoh.adoc
Labels: priority.High, type.Task

#139 Bug fix on startSession
  docs/team/johndoe.adoc
  src/main/java/seedu/system/logic/commands/outofsession/DeleteParticipationCommand.java
  src/main/java/seedu/system/logic/commands/outofsession/StartSessionCommand.java
  src/main/java/seedu/system/model/participation/Participation.java
Labels: severity.Medium

#140 Fix bug in ranklist command parser
  src/main/java/seedu/system/logic/parser/ParserUtil.java
Labels: severity.Medium, type.Bug, type.Task
